export const VEHICLE_TUNE_ENGINE = {
    STANDARTENGINE: 0,
    EMS1: 1,
    EMS2: 2,
    EMS3: 3,
    EMS4: 4,
};

export const VEHICLE_TUNE_BRAKES = {
    STANDARTBRAKES: 0,
    STREETBRAKES: 1,
    SPORTBRAKES: 2,
    RACEBRAKES: 3,
};

export const VEHICLE_TUNE_TRANSMISSION = {
    STANDARTTRANSMISSION: 0,
    STREETTRANSMISSION: 1,
    SPORTTRANSMISSION: 2,
    RACETRANSMISSION: 3,
};

export const VEHICLE_TUNE_SUSPENSION = {
    STANDARTSUSPENSION: 0,
    LOWERSUSPENSION: 1,
    STREETSUSPENSION: 2,
    SPORTSUSPENSION: 3,
    RACESUSPENSION: 4,

};

export const VEHICLE_TUNE_ARMOUR = {
    NOARMOUR: 0,
    ARMOUR20PERCENT: 1,
    ARMOUR40PERCENT: 2,
    ARMOUR60PERCENT: 3,
    ARMOUR80PERCENT: 4,
    ARMOUR100PERCENT: 5,
};

export const VEHICLE_TUNE_TURBO = {
    NONE: 0,
    TURBOTUNING: 1,
};

export const VEHICLE_TUNE_XENON = {
    STANDARTLIGHTS: 0,
    XENONLIGHTS: 1,
};